CREATE TABLE IF NOT EXISTS proposal (
    id BIGSERIAL PRIMARY KEY,
    external_id UUID UNIQUE NOT NULL,
    identity_document VARCHAR(14) NOT NULL,
    email VARCHAR(150) NOT NULL,
    name VARCHAR(150) NOT NULL,
    salary DECIMAL NOT NULL,
    address VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW(),
    updated TIMESTAMP NOT NULL DEFAULT NOW()
);
